# Generated by Django 3.1.4 on 2021-07-13 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 7, 13, 18, 21, 41, 694038, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
